insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (1, 'Poliza1_Vida', 'Seguro de vida con cobertura amplia', 6, 2);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (2, 'Poliza2_Vida', 'Seguro de auto básico', 4, 1);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (3, 'Poliza3_Vida', 'Seguro de hogar con protección contra incendios', 8, 2);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (4, 'Poliza1_Auto', 'Seguro de salud con cobertura dental', 2, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (5, 'Poliza2_Auto', 'Seguro de viaje internacional con asistencia médica', 10, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (6, 'Poliza3_Auto', 'Seguro de mascotas con cobertura de accidentes', 6, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (7, 'Poliza1_Hogar', 'Seguro de responsabilidad civil para negocios', 9, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (8, 'Poliza2_Hogar', 'Seguro de accidentes personales con invalidez permanente', 7, 5);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (9, 'Poliza3_Hogar', 'Seguro de protección de identidad contra robo de datos', 9, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (10, 'Poliza1_Salud', 'Seguro de equipos electrónicos con cobertura de daños', 10, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (11, 'Poliza2_Salud', 'Seguro de vida con cobertura amplia', 1, 2);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (12, 'Poliza3_Salud', 'Seguro de auto básico', 7, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (13, 'Poliza1_Viaje', 'Seguro de hogar con protección contra incendios', 3, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (14, 'Poliza2_Viaje', 'Seguro de salud con cobertura dental', 10, 5);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (15, 'Poliza3_Viaje', 'Seguro de viaje internacional con asistencia médica', 1, 1);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (16, 'Poliza1_Mascotas', 'Seguro de mascotas con cobertura de accidentes', 6, 3);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (17, 'Poliza2_Mascotas', 'Seguro de responsabilidad civil para negocios', 10, 3);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (18, 'Poliza3_Mascotas', 'Seguro de accidentes personales con invalidez permanente', 6, 3);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (19, 'Poliza1_Accidentes', 'Seguro de protección de identidad contra robo de datos', 7, 5);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (20, 'Poliza2_Accidentes', 'Seguro de equipos electrónicos con cobertura de daños', 9, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (21, 'Poliza3_Accidentes', 'Seguro de vida con cobertura amplia', 6, 3);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (22, 'Poliza1_ResponsabilidadCivil', 'Seguro de auto básico', 1, 1);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (23, 'Poliza2_ResponsabilidadCivil', 'Seguro de hogar con protección contra incendios', 3, 4);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (24, 'Poliza3_ResponsabilidadCivil', 'Seguro de salud con cobertura dental', 4, 5);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (25, 'Poliza1_Desempleo', 'Seguro de viaje internacional con asistencia médica', 6, 3);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (26, 'Poliza2_Desempleo', 'Seguro de mascotas con cobertura de accidentes', 7, 2);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (27, 'Poliza3_Desempleo', 'Seguro de responsabilidad civil para negocios', 10, 1);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (28, 'Poliza1_Invalidez', 'Seguro de accidentes personales con invalidez permanente', 2, 5);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (29, 'Poliza2_Invalidez', 'Seguro de protección de identidad contra robo de datos', 1, 3);
insert into SEGURO_G26473471.PRODUCTO (cod_producto, nb_producto, descripcion, cod_tipo_producto, calificacion) values (30, 'Poliza3_Invalidez', 'Seguro de equipos electrónicos con cobertura de daños', 3, 3);
