insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (1, 'Suspendido');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (2, 'Expirado');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (3, 'Expirado');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (4, 'Renovado');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (5, 'Activo');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (6, 'En espera de aprobación');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (7, 'Inactivo');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (8, 'En proceso de renovación');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (9, 'Terminado');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (10, 'En reclamación');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (11, 'En reclamación');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (12, 'Pendiente');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (13, 'Vigente');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (14, 'Pendiente');
insert into EVALUACION_SERVICIO (cod_estado, descrip_estado) values (15, 'Inactivo');
