DROP SCHEMA IF EXISTS SEGURO_G26473471 CASCADE;

CREATE SCHEMA SEGURO_G26473471;

-- Create PRODUCTO table
CREATE TABLE SEGURO_G26473471.PRODUCTO (
    COD_PRODUCTO INT PRIMARY KEY,
    NB_PRODUCTO VARCHAR(25),
    DESCRIP_PRODUCTO VARCHAR(25),
    COD_TIPO_PRODUCTO VARCHAR(25),
    NB_TIPO_PRODUCTO VARCHAR(25),
    CALIFICACION INT
);

-- Create CLIENTE table
CREATE TABLE SEGURO_G26473471.CLIENTE (
    COD_CLIENTE INT PRIMARY KEY,
    NB_CLIENTE VARCHAR(25),
    CI_RIF VARCHAR(25),
    TELEFONO VARCHAR(25),
    DIRECCION VARCHAR(25),
    SEXO VARCHAR(25),
    EMAIL VARCHAR(25)
);

-- Create EVALUACION_SERVICIO table
CREATE TABLE SEGURO_G26473471.EVALUACION_SERVICIO (
    COD_EVALUACION_SERVICIO INT PRIMARY KEY,
    NB_DESCRIPCION VARCHAR(25)
);

-- Create CONTRATO table
CREATE TABLE SEGURO_G26473471.CONTRATO (
    NRO_CONTRATO INT PRIMARY KEY,
    DESCRIP_CONTRATO VARCHAR(25)
);

-- Create ESTADO_CONTRATO table
CREATE TABLE SEGURO_G26473471.ESTADO_CONTRATO (
    COD_ESTADO INT PRIMARY KEY,
    DESCRIP_ESTADO VARCHAR(25)
);

-- Create FACT_METAS table
CREATE TABLE SEGURO_G26473471.FACT_METAS (
    FECHA_INICIO_META TIMESTAMP,
    PRODUCTO_ID INT,
    FECHA_FIN_META TIMESTAMP,
    MONTO_META_VENTA INT,
    META_RENOVACION INT,
    META_ASEGURADOS INT,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(COD_PRODUCTO)
);

-- Create FACT_EVALUACION_SERVICIO table
CREATE TABLE SEGURO_G26473471.FACT_EVALUACION_SERVICIO (
    FECHA_EVALUACION TIMESTAMP,
    COD_CLIENTE INT,
    COD_PRODUCTO INT,
    COD_EVALUACION_SERVICIO INT,
    CANTIDAD INT,
    RECOMIENDA_AMIGO BOOL,
    FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
    FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO),
    FOREIGN KEY (COD_EVALUACION_SERVICIO) REFERENCES EVALUACION_SERVICIO(COD_EVALUACION_SERVICIO)
);

-- Create FACT_REGISTRO_CONTRATO table
CREATE TABLE SEGURO_G26473471.FACT_REGISTRO_CONTRATO (
    FECHA_INICIO_CONTRATO TIMESTAMP,
    FECHA_FIN_CONTRATO TIMESTAMP,
    COD_CLIENTE INT,
    COD_PRODUCTO INT,
    COD_CONTRATO INT,
    COD_ESTADO INT,
    MONTO INT,
    CANTIDAD INT,
    CANTIDAD_CLIENTE INT,
    CANTIDAD_PRODUCTO INT,
    CANTIDAD_CONTRATO INT,
    FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
    FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO),
    FOREIGN KEY (COD_CONTRATO) REFERENCES CONTRATO(NRO_CONTRATO),
    FOREIGN KEY (COD_ESTADO) REFERENCES ESTADO_CONTRATO(COD_ESTADO)
);